### PR TITLE
Fix Dagger2 shifting sands

### PR DESCRIPTION
**Pull request by rjrjr**

### CODE REVIEW

**Comment by rjrjr** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Mortar (Parent) .................................... SUCCESS [  0.455 s]
[INFO] Mortar ............................................. SUCCESS [  6.010 s]
[INFO] Dagger1 Support .................................... SUCCESS [  4.463 s]
[INFO] Dagger2 Support .................................... SUCCESS [  2.115 s]
[INFO] Hello Mortar ....................................... SUCCESS [  9.320 s]
[INFO] Mortar Sample ...................................... SUCCESS [ 10.812 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.181 s
[INFO] Finished at: 2015-01-22T18:20:29-08:00
[INFO] Final Memory: 58M/422M
[INFO] ------------------------------------------------------------------------
```

**Comment by pyricau** [comment]
LGTM :+1:

**Comment by chrisjenx** [comment]
@pyricau @rjrjr can you release another snapshot? The latest one seems to have not picked up this merge. (The source shows the code of the previous snapshot, and the bug with name mismatch still exists).

**Comment by rjrjr** [comment]
Fixed.

**Comment by chrisjenx** [comment]
Thanks.

**Comment by rjrjr** [comment]
Thanks for using it!

**Comment by chrisjenx** [comment]
Dagger2 + Mortar + Flow. Pretty much 100%, just testing is  a bit tricky.

**Pull request merged**
